# Generated by Django 4.1.4 on 2023-03-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_altkategori_urun_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='seri',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.serino'),
        ),
    ]
