# Generated by Django 4.1.4 on 2023-04-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0010_alter_sepet_adet_alter_sepet_toplam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='adet',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='toplam',
            field=models.BigIntegerField(),
        ),
    ]
